### ISSUE TITLE
Custom python API for easy to use launch files

### ISSUE THREAD

**Issue by afxalz** [ctu-mrs/ros2_uav_example#11]

**Comment by afxalz** [comment]
- Added a launch helper that provides easy utility functions to add:
  - launch arg to get arguments at runtime
  - a `custom_config` arg to get config file names same as ROS1
  - loading of all yaml files in a directory
  - loading of a single yaml file
  - remaps
  - verbose output of the params being used for node creation

**Comment by afxalz** [comment]
# TODO:
- [ ] test for easy testing the helper module
- [ ] example for one of the complex nodes from MRS
- [ ] function to add remaps as list of tuples
- [ ] function to add more than one node in the same container
- [ ] function to add more than one `custom_config`-like arguments
